import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 9개 카테고리 3-티어 구조.
 * [서브] 01-03  Linux · Network · Container        (기반, 필수만)
 * [메인] 04-06  Kubernetes · Observability · CI/CD  (핵심, 빠짐없이)
 * [성장] 07-09  IaC · Security · SRE               (역량 확장, 필수만)
 *
 * 각 카테고리 디렉토리의 _category_.json에서 index.md를 카테고리 링크로
 * 지정해 사이드바의 중복 표시를 제거한다.
 */
const sidebars: SidebarsConfig = {
  wikiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
