import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    {
      type: 'category',
      label: '1. Linux',
      link: {type: 'doc', id: 'linux/index'},
      items: [
        {type: 'doc', id: 'linux/linux-distro-comparison', label: '배포판 비교'},
        {type: 'doc', id: 'linux/filesystem-hierarchy', label: '파일시스템 구조'},
        {type: 'doc', id: 'linux/user-group-permission', label: '사용자·그룹·퍼미션'},
        {type: 'doc', id: 'linux/package-management', label: '패키지 관리'},
        {type: 'doc', id: 'linux/systemd', label: 'systemd'},
        {type: 'doc', id: 'linux/boot-process', label: '부트 프로세스'},
        {type: 'doc', id: 'linux/process-management', label: '프로세스 관리'},
        {type: 'doc', id: 'linux/crontab', label: 'crontab'},
        {type: 'doc', id: 'linux/disk-lvm', label: '디스크·LVM'},
        {type: 'doc', id: 'linux/iproute2', label: 'iproute2'},
        {type: 'doc', id: 'linux/dns-config', label: 'DNS 설정'},
        {type: 'doc', id: 'linux/firewall', label: '방화벽'},
        {type: 'doc', id: 'linux/ssh', label: 'SSH'},
        {type: 'doc', id: 'linux/bash-script', label: 'Bash 스크립트'},
        {type: 'doc', id: 'linux/automation-scripts', label: '자동화 스크립트'},
        {type: 'doc', id: 'linux/python-linux', label: 'Python 자동화'},
        {type: 'doc', id: 'linux/syslog-journald', label: 'syslog·journald'},
        {type: 'doc', id: 'linux/log-rotation', label: '로그 로테이션'},
        {type: 'doc', id: 'linux/log-management', label: '로그 관리'},
        {type: 'doc', id: 'linux/cpu-performance', label: 'CPU 성능'},
        {type: 'doc', id: 'linux/memory-oom', label: '메모리·OOM'},
        {type: 'doc', id: 'linux/disk-io-performance', label: '디스크 I/O'},
        {type: 'doc', id: 'linux/network-performance', label: '네트워크 성능'},
        {type: 'doc', id: 'linux/ebpf-performance', label: 'eBPF 분석'},
      ],
    },
    {
      type: 'category',
      label: '2. Network',
      link: {type: 'doc', id: 'network/index'},
      items: [
        {type: 'doc', id: 'network/osi-tcpip', label: 'OSI·TCP/IP'},
        {type: 'doc', id: 'network/dns-how-it-works', label: 'DNS 동작 원리'},
        {type: 'doc', id: 'network/http-https-tls', label: 'HTTP·TLS'},
        {type: 'doc', id: 'network/tcp-vs-udp', label: 'TCP vs UDP'},
        {type: 'doc', id: 'network/subnet-cidr', label: '서브넷·CIDR'},
        {type: 'doc', id: 'network/vpc-design', label: 'VPC 설계'},
        {type: 'doc', id: 'network/load-balancer', label: '로드밸런서'},
        {type: 'doc', id: 'network/reverse-proxy', label: '리버스 프록시'},
        {type: 'doc', id: 'network/nat-portforward', label: 'NAT·포트포워딩'},
        {type: 'doc', id: 'network/docker-network', label: 'Docker 네트워크'},
        {type: 'doc', id: 'network/cni-comparison', label: 'CNI 비교'},
        {type: 'doc', id: 'network/k8s-service-ingress', label: 'Service·Ingress'},
        {type: 'doc', id: 'network/coredns', label: 'CoreDNS'},
        {type: 'doc', id: 'network/service-mesh', label: '서비스 메시'},
        {type: 'doc', id: 'network/ebpf-networking', label: 'eBPF 네트워킹'},
        {type: 'doc', id: 'network/network-troubleshooting', label: '네트워크 트러블슈팅'},
        {type: 'doc', id: 'network/network-tuning', label: '네트워크 튜닝'},
      ],
    },
    {
      type: 'category',
      label: '3. Container',
      link: {type: 'doc', id: 'container/index'},
      items: [
        {type: 'doc', id: 'container/container-vs-vm', label: '컨테이너 vs VM'},
        {type: 'doc', id: 'container/container-linux-internals', label: '컨테이너 내부 구조'},
        {type: 'doc', id: 'container/docker-basics', label: 'Docker 기본'},
        {type: 'doc', id: 'container/container-lifecycle', label: '컨테이너 라이프사이클'},
        {type: 'doc', id: 'container/dockerfile-best-practices', label: 'Dockerfile'},
        {type: 'doc', id: 'container/multistage-build', label: '멀티스테이지 빌드'},
        {type: 'doc', id: 'container/image-optimization', label: '이미지 경량화'},
        {type: 'doc', id: 'container/container-registry', label: '컨테이너 레지스트리'},
        {type: 'doc', id: 'container/docker-network', label: 'Docker 네트워크'},
        {type: 'doc', id: 'container/docker-volume', label: 'Volume·Bind Mount'},
        {type: 'doc', id: 'container/data-persistence', label: '데이터 지속성'},
      ],
    },
    {
      type: 'category',
      label: '4. Kubernetes',
      link: {type: 'doc', id: 'kubernetes/index'},
      items: [
        {type: 'doc', id: 'kubernetes/kubernetes-2025-2026-release-overview', label: 'v1.33~v1.36 릴리즈'},
      ],
    },
    {
      type: 'category',
      label: '5. IaC',
      link: {type: 'doc', id: 'iac/index'},
      items: [],
    },
    {
      type: 'category',
      label: '6. CICD',
      link: {type: 'doc', id: 'cicd/index'},
      items: [],
    },
    {
      type: 'category',
      label: '7. GitOps',
      link: {type: 'doc', id: 'gitops/index'},
      items: [],
    },
    {
      type: 'category',
      label: '8. Observability',
      link: {type: 'doc', id: 'observability/index'},
      items: [],
    },
    {
      type: 'category',
      label: '9. Security',
      link: {type: 'doc', id: 'security/index'},
      items: [],
    },
    {
      type: 'category',
      label: '10. SRE',
      link: {type: 'doc', id: 'sre/index'},
      items: [],
    },
  ],
};

export default sidebars;
