import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    {
      type: 'category',
      label: '1. Linux',
      link: {type: 'doc', id: 'linux/index'},
      items: [
        {type: 'doc', id: 'linux/linux-distro-comparison', label: '배포판 비교'},
        {type: 'doc', id: 'linux/filesystem-hierarchy', label: '파일시스템 구조'},
        {type: 'doc', id: 'linux/user-group-permission', label: '사용자·그룹·퍼미션'},
        {type: 'doc', id: 'linux/package-management', label: '패키지 관리'},
        {type: 'doc', id: 'linux/systemd', label: 'systemd'},
        {type: 'doc', id: 'linux/boot-process', label: '부트 프로세스'},
        {type: 'doc', id: 'linux/process-management', label: '프로세스 관리'},
        {type: 'doc', id: 'linux/crontab', label: 'crontab'},
        {type: 'doc', id: 'linux/disk-lvm', label: '디스크·LVM'},
        {type: 'doc', id: 'linux/iproute2', label: 'iproute2'},
        {type: 'doc', id: 'linux/dns-config', label: 'DNS 설정'},
        {type: 'doc', id: 'linux/firewall', label: '방화벽'},
        {type: 'doc', id: 'linux/ssh', label: 'SSH'},
        {type: 'doc', id: 'linux/bash-script', label: 'Bash 스크립트'},
        {type: 'doc', id: 'linux/automation-scripts', label: '자동화 스크립트'},
        {type: 'doc', id: 'linux/python-linux', label: 'Python 자동화'},
        {type: 'doc', id: 'linux/syslog-journald', label: 'syslog·journald'},
        {type: 'doc', id: 'linux/log-rotation', label: '로그 로테이션'},
        {type: 'doc', id: 'linux/log-management', label: '로그 관리'},
        {type: 'doc', id: 'linux/cpu-performance', label: 'CPU 성능'},
        {type: 'doc', id: 'linux/memory-oom', label: '메모리·OOM'},
        {type: 'doc', id: 'linux/disk-io-performance', label: '디스크 I/O'},
        {type: 'doc', id: 'linux/network-performance', label: '네트워크 성능'},
        {type: 'doc', id: 'linux/ebpf-performance', label: 'eBPF 분석'},
      ],
    },
    {
      type: 'category',
      label: '2. Network',
      link: {type: 'doc', id: 'network/index'},
      items: [
        {type: 'doc', id: 'network/osi-tcpip', label: 'OSI·TCP/IP'},
        {type: 'doc', id: 'network/dns-how-it-works', label: 'DNS 동작 원리'},
        {type: 'doc', id: 'network/http-https-tls', label: 'HTTP·TLS'},
        {type: 'doc', id: 'network/tcp-vs-udp', label: 'TCP vs UDP'},
        {type: 'doc', id: 'network/subnet-cidr', label: '서브넷·CIDR'},
        {type: 'doc', id: 'network/vpc-design', label: 'VPC 설계'},
        {type: 'doc', id: 'network/load-balancer', label: '로드밸런서'},
        {type: 'doc', id: 'network/reverse-proxy', label: '리버스 프록시'},
        {type: 'doc', id: 'network/nat-portforward', label: 'NAT·포트포워딩'},
        {type: 'doc', id: 'network/docker-network', label: 'Docker 네트워크'},
        {type: 'doc', id: 'network/cni-comparison', label: 'CNI 비교'},
        {type: 'doc', id: 'network/k8s-service-ingress', label: 'Service·Ingress'},
        {type: 'doc', id: 'network/coredns', label: 'CoreDNS'},
        {type: 'doc', id: 'network/service-mesh', label: '서비스 메시'},
        {type: 'doc', id: 'network/ebpf-networking', label: 'eBPF 네트워킹'},
        {type: 'doc', id: 'network/network-troubleshooting', label: '네트워크 트러블슈팅'},
        {type: 'doc', id: 'network/network-tuning', label: '네트워크 튜닝'},
      ],
    },
    {
      type: 'category',
      label: '3. Container',
      link: {type: 'doc', id: 'container/index'},
      items: [
        {type: 'doc', id: 'container/container-vs-vm', label: '컨테이너 vs VM'},
        {type: 'doc', id: 'container/container-linux-internals', label: '컨테이너 내부 구조'},
        {type: 'doc', id: 'container/docker-basics', label: 'Docker 기본'},
        {type: 'doc', id: 'container/container-lifecycle', label: '컨테이너 라이프사이클'},
        {type: 'doc', id: 'container/dockerfile-best-practices', label: 'Dockerfile'},
        {type: 'doc', id: 'container/multistage-build', label: '멀티스테이지 빌드'},
        {type: 'doc', id: 'container/image-optimization', label: '이미지 경량화'},
        {type: 'doc', id: 'container/container-registry', label: '컨테이너 레지스트리'},
        {type: 'doc', id: 'container/docker-network', label: 'Docker 네트워크'},
        {type: 'doc', id: 'container/docker-volume', label: 'Volume·Bind Mount'},
        {type: 'doc', id: 'container/data-persistence', label: '데이터 지속성'},
        {type: 'doc', id: 'container/docker-compose', label: 'Docker Compose'},
        {type: 'doc', id: 'container/container-resources', label: '리소스 제한'},
        {type: 'doc', id: 'container/container-monitoring', label: '컨테이너 모니터링'},
        {type: 'doc', id: 'container/container-security', label: '컨테이너 보안'},
        {type: 'doc', id: 'container/containerd-vs-docker', label: 'containerd vs Docker'},
        {type: 'doc', id: 'container/oci-standards', label: 'OCI 표준'},
        {type: 'doc', id: 'container/container-runtime-comparison', label: '런타임 비교'},
      ],
    },
    {
      type: 'category',
      label: '4. Kubernetes',
      link: {type: 'doc', id: 'kubernetes/index'},
      items: [
        {type: 'doc', id: 'kubernetes/k8s-architecture', label: '클러스터 구성요소'},
        {type: 'doc', id: 'kubernetes/control-plane', label: 'Control Plane'},
        {type: 'doc', id: 'kubernetes/worker-node', label: 'Worker Node'},
        {type: 'doc', id: 'kubernetes/cluster-setup', label: '클러스터 구축'},
        {type: 'doc', id: 'kubernetes/pod-replicaset-deployment', label: 'Pod·Deployment'},
        {type: 'doc', id: 'kubernetes/service-ingress-gateway', label: 'Service·Ingress'},
        {type: 'doc', id: 'kubernetes/configmap-secret', label: 'ConfigMap·Secret'},
        {type: 'doc', id: 'kubernetes/namespace-quota', label: 'Namespace·Quota'},
        {type: 'doc', id: 'kubernetes/job-daemonset-statefulset', label: 'Job·DaemonSet·SS'},
        {type: 'doc', id: 'kubernetes/pv-pvc-storageclass', label: 'PV·PVC·StorageClass'},
        {type: 'doc', id: 'kubernetes/kubectl-tips', label: 'kubectl 팁'},
        {type: 'doc', id: 'kubernetes/pod-scheduling', label: '파드 배치 전략'},
        {type: 'doc', id: 'kubernetes/rolling-update', label: '롤링 업데이트·롤백'},
        {type: 'doc', id: 'kubernetes/cluster-upgrade', label: '클러스터 업그레이드'},
        {type: 'doc', id: 'kubernetes/autoscaling', label: '오토스케일링'},
        {type: 'doc', id: 'kubernetes/service-discovery-coredns', label: '서비스 디스커버리'},
        {type: 'doc', id: 'kubernetes/ingress-controller-comparison', label: 'Ingress Controller'},
        {type: 'doc', id: 'kubernetes/network-policy', label: '네트워크 폴리시'},
        {type: 'doc', id: 'kubernetes/kustomize', label: 'Kustomize'},
        {type: 'doc', id: 'kubernetes/helm', label: 'Helm'},
        {type: 'doc', id: 'kubernetes/k9s-lens-tools', label: 'k9s·Lens·kubectx'},
        {type: 'doc', id: 'kubernetes/pod-debugging', label: '파드 디버깅'},
        {type: 'doc', id: 'kubernetes/k8s-error-messages', label: '에러 유형과 해결'},
        {type: 'doc', id: 'kubernetes/finalizer-stuck-resources', label: 'Finalizer·Stuck'},
        {type: 'doc', id: 'kubernetes/kubernetes-2025-2026-release-overview', label: 'v1.33~v1.36 릴리즈'},
      ],
    },
    {
      type: 'category',
      label: '5. IaC',
      link: {type: 'doc', id: 'iac/index'},
      items: [
        {type: 'doc', id: 'iac/iac-overview', label: 'IaC란'},
        {type: 'doc', id: 'iac/iac-declarative-vs-imperative', label: '선언형 vs 명령형'},
        {type: 'doc', id: 'iac/iac-cm-vs-provisioning', label: 'CM vs 프로비저닝'},
        {type: 'doc', id: 'iac/terraform-basics', label: 'Terraform 기초'},
        {type: 'doc', id: 'iac/terraform-core-components', label: 'Terraform 구성요소'},
        {type: 'doc', id: 'iac/terraform-modules', label: 'Terraform 모듈'},
        {type: 'doc', id: 'iac/terraform-state', label: 'Terraform State'},
        {type: 'doc', id: 'iac/terraform-workspace', label: 'Workspace·디렉토리'},
        {type: 'doc', id: 'iac/terraform-cloud-atlantis', label: 'TF Cloud·Atlantis'},
        {type: 'doc', id: 'iac/ansible-basics', label: 'Ansible 기초'},
        {type: 'doc', id: 'iac/ansible-module-handler', label: 'Module·Handler'},
        {type: 'doc', id: 'iac/ansible-variables', label: '변수·반복문·조건문'},
        {type: 'doc', id: 'iac/ansible-roles-galaxy', label: 'Role·Galaxy'},
        {type: 'doc', id: 'iac/ansible-vs-terraform', label: 'Ansible vs Terraform'},
        {type: 'doc', id: 'iac/pulumi', label: 'Pulumi'},
        {type: 'doc', id: 'iac/packer', label: 'Packer'},
        {type: 'doc', id: 'iac/cloudformation-cdk', label: 'CFn vs CDK'},
        {type: 'doc', id: 'iac/iac-directory-structure', label: '디렉토리 구조 설계'},
        {type: 'doc', id: 'iac/iac-module-versioning', label: '모듈 버전 관리'},
        {type: 'doc', id: 'iac/iac-secret-management', label: '시크릿 관리'},
        {type: 'doc', id: 'iac/iac-code-review', label: '코드 리뷰 체크리스트'},
      ],
    },
    {
      type: 'category',
      label: '6. CICD',
      link: {type: 'doc', id: 'cicd/index'},
      items: [
        {type: 'doc', id: 'cicd/cicd-overview', label: 'CI/CD 개요'},
        {type: 'doc', id: 'cicd/cicd-delivery-vs-deployment', label: 'CD vs CD 차이'},
        {type: 'doc', id: 'cicd/cicd-deployment-strategies', label: '배포 전략'},
        {type: 'doc', id: 'cicd/cicd-branching-strategy', label: '브랜치 전략'},
        {type: 'doc', id: 'cicd/jenkins-install', label: 'Jenkins 설치'},
        {type: 'doc', id: 'cicd/jenkins-job-pipeline', label: 'Job·Pipeline'},
        {type: 'doc', id: 'cicd/jenkins-jenkinsfile', label: 'Jenkinsfile'},
        {type: 'doc', id: 'cicd/jenkins-multibranch', label: 'Multibranch'},
        {type: 'doc', id: 'cicd/jenkins-agents', label: 'Agents'},
        {type: 'doc', id: 'cicd/jenkins-plugins', label: 'Plugins'},
        {type: 'doc', id: 'cicd/jenkins-operations', label: 'Jenkins 운영'},
        {type: 'doc', id: 'cicd/github-actions-basics', label: 'GA 기초'},
        {type: 'doc', id: 'cicd/github-actions-triggers', label: 'GA 트리거'},
        {type: 'doc', id: 'cicd/github-actions-security', label: 'GA 보안·OIDC'},
        {type: 'doc', id: 'cicd/github-actions-build', label: 'GA 빌드·배포'},
        {type: 'doc', id: 'cicd/github-actions-container', label: 'GA 컨테이너'},
        {type: 'doc', id: 'cicd/github-actions-cache', label: 'GA 캐시·재사용'},
        {type: 'doc', id: 'cicd/cicd-unit-test', label: '단위 테스트'},
        {type: 'doc', id: 'cicd/cicd-integration-test', label: '통합 테스트'},
        {type: 'doc', id: 'cicd/cicd-performance-test', label: '성능 테스트'},
        {type: 'doc', id: 'cicd/cicd-code-quality', label: '코드 품질'},
        {type: 'doc', id: 'cicd/cicd-pipeline-design', label: '파이프라인 설계'},
        {type: 'doc', id: 'cicd/cicd-notifications', label: '빌드 결과 알림'},
        {type: 'doc', id: 'cicd/cicd-troubleshooting', label: '파이프라인 트러블슈팅'},
      ],
    },
    {
      type: 'category',
      label: '7. GitOps',
      link: {type: 'doc', id: 'gitops/index'},
      items: [
        {type: 'doc', id: 'gitops/gitops-overview', label: 'GitOps란'},
        {type: 'doc', id: 'gitops/gitops-push-pull-model', label: 'Push vs Pull'},
        {type: 'doc', id: 'gitops/gitops-four-principles', label: 'GitOps 4원칙'},
        {type: 'doc', id: 'gitops/argocd-install', label: 'ArgoCD 설치'},
        {type: 'doc', id: 'gitops/argocd-application-project', label: 'Application·Project'},
        {type: 'doc', id: 'gitops/argocd-sync-policy', label: 'Sync 정책'},
        {type: 'doc', id: 'gitops/argocd-kustomize', label: 'ArgoCD Kustomize'},
        {type: 'doc', id: 'gitops/argocd-helm', label: 'ArgoCD Helm'},
        {type: 'doc', id: 'gitops/argocd-image-updater', label: 'Image Updater'},
        {type: 'doc', id: 'gitops/argocd-rbac-sso', label: 'RBAC·SSO'},
        {type: 'doc', id: 'gitops/argocd-monitoring', label: 'ArgoCD 모니터링'},
        {type: 'doc', id: 'gitops/argocd-security', label: 'ArgoCD 보안'},
        {type: 'doc', id: 'gitops/argocd-orphaned-resources', label: 'Orphaned Resource'},
        {type: 'doc', id: 'gitops/flux-overview', label: 'Flux 소개·비교'},
        {type: 'doc', id: 'gitops/flux-basics', label: 'Flux 기본'},
        {type: 'doc', id: 'gitops/helm-chart', label: 'Helm Chart'},
        {type: 'doc', id: 'gitops/kustomize-basics', label: 'Kustomize'},
        {type: 'doc', id: 'gitops/helm-vs-kustomize', label: 'Helm vs Kustomize'},
        {type: 'doc', id: 'gitops/argo-rollouts-overview', label: 'Argo Rollouts 소개'},
        {type: 'doc', id: 'gitops/argo-rollouts-bluegreen', label: 'Blue/Green 실습'},
        {type: 'doc', id: 'gitops/argo-rollouts-canary', label: 'Canary 실습'},
        {type: 'doc', id: 'gitops/argo-rollouts-analysis', label: 'Analysis·자동 롤백'},
      ],
    },
    {
      type: 'category',
      label: '8. Observability',
      link: {type: 'doc', id: 'observability/index'},
      items: [
        {type: 'doc', id: 'observability/observability-vs-monitoring', label: '모니터링 vs 옵저버빌리티'},
        {type: 'doc', id: 'observability/three-pillars', label: '3 Pillars'},
        {type: 'doc', id: 'observability/monitoring-anti-patterns', label: '모니터링 Anti-Pattern'},
        {type: 'doc', id: 'observability/monitoring-signals', label: 'RED·USE·Golden Signals'},
        {type: 'doc', id: 'observability/prometheus-install', label: 'Prometheus 설치'},
        {type: 'doc', id: 'observability/promql-basics', label: 'PromQL'},
        {type: 'doc', id: 'observability/alertmanager', label: 'Alertmanager'},
        {type: 'doc', id: 'observability/grafana-dashboard', label: 'Grafana 대시보드'},
        {type: 'doc', id: 'observability/elk-stack', label: 'ELK Stack'},
        {type: 'doc', id: 'observability/fluentd-fluent-bit', label: 'Fluentd·Fluent Bit'},
        {type: 'doc', id: 'observability/loki', label: 'Loki'},
        {type: 'doc', id: 'observability/k8s-logging-strategy', label: 'K8s 로깅 전략'},
        {type: 'doc', id: 'observability/distributed-tracing', label: '분산 트레이싱'},
        {type: 'doc', id: 'observability/opentelemetry', label: 'OpenTelemetry'},
        {type: 'doc', id: 'observability/jaeger-tempo', label: 'Jaeger·Tempo'},
        {type: 'doc', id: 'observability/alerting-principles', label: '알림 설계 원칙'},
        {type: 'doc', id: 'observability/grafana-alerting', label: 'Grafana 알림'},
        {type: 'doc', id: 'observability/alert-integrations', label: 'Slack·PagerDuty'},
        {type: 'doc', id: 'observability/monitoring-three-tier-app', label: '3계층 앱 모니터링'},
        {type: 'doc', id: 'observability/k8s-monitoring-stack', label: 'K8s 모니터링 스택'},
      ],
    },
    {
      type: 'category',
      label: '9. Security',
      link: {type: 'doc', id: 'security/index'},
      items: [],
    },
    {
      type: 'category',
      label: '10. SRE',
      link: {type: 'doc', id: 'sre/index'},
      items: [],
    },
  ],
};

export default sidebars;
